### ISSUE TITLE
no Intellisense after installing IonicPack

### ISSUE THREAD

**Issue by amirjalali1** [madskristensen/IonicPack#2]
after installing ionicpack still there isn't any Intellisense  avaliable.

do i have to do anything else?

vs 2015 enterprise
resharper 10.0.1
taco latest version
web essential 2015.1

**Comment by madskristensen** [comment]
It's due to ReSharper that replaces the HTML editor with its own editor. You need to disable ReSharper or just the HTML takeover that it does.
