### ISSUE TITLE
Extension causes Visual Studio 2015 to crash

### ISSUE THREAD

**Issue by CodeAbuser** [madskristensen/IonicPack#3]
When editing an html file the following error is added to the ActivityLog.xml and then Visual Studio crashes and restarts. Disabling this extension causes the error to cease.

  <entry>
    <record>788</record>
    <time>2016/03/18 16:15:38.869</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.Html.Editor.Completion.HtmlCompletionSource.RemoveDuplicateEntriesAndSort(List`1 completions, String triggerText)&#x000D;&#x000A;   at Microsoft.Html.Editor.Completion.HtmlCompletionSource.PopulateCompletionList(Int32 position, ICompletionSession session, IList`1 completionSets)&#x000D;&#x000A;   at Microsoft.Html.Editor.Completion.HtmlCompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionBroker.TriggerCompletion(ITextView textView)&#x000D;&#x000A;   at Microsoft.Web.Editor.Completion.CompletionController.TriggerCompletion()&#x000D;&#x000A;   at Microsoft.Web.Editor.Completion.CompletionController.ShowCompletion(Boolean autoShownCompletion)&#x000D;&#x000A;   at Microsoft.Web.Editor.Completion.CompletionController.OnPostTypeChar(Char typedCharacter)&#x000D;&#x000A;   at Microsoft.Html.Editor.Completion.HtmlCompletionController.OnPostTypeChar(Char typedCharacter)&#x000D;&#x000A;   at Microsoft.Web.Editor.Completion.TypingCommandHandler.OnPostTypeChar(Char typedChar)&#x000D;&#x000A;   at Microsoft.Web.Editor.Completion.TypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.Html.Editor.Commands.HtmlTypingCommandHandler.PostProcessInvoke(CommandResult result, Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.Controller.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.Web.Editor.Controller.ViewController.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.Html.Editor.Commands.HtmlMainController.Invoke(Guid group, Int32 id, Object inputArg, Object&amp; outputArg)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Interop.CommandTargetToOleShim.Exec(Guid&amp; guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid&amp; pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)</description>
  </entry>

**Comment by madskristensen** [comment]
Can you show how I can reproduce this? What exactly did you type and where?

**Comment by madskristensen** [comment]
Wait, do you have ReSharper installed?

**Comment by madskristensen** [comment]
Nothing in the stacktrace points to the Ionic Pack extension. I've opened the bug on the HTML editor team

**Comment by CherryAnt** [comment]
Hi,
Then how do I fix that?
Thanks
